name: CD

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Plugin
        run: ./gradlew clean build

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
